### ISSUE TITLE
Design suggestions for the local health/status page

### ISSUE THREAD

**Issue by nckrtl** [spatie/laravel-health#10]
As the other options for opening an issue led to a 404, I decided to create this issue to suggest some UI improvements for the local health page.

This week I had to install this package for a client. Everything went really smooth setting things up. One of the features I think is really cool, is the local health page that can function as a status page for the checks that are set up.

Although the page is really clear and recently got an update (#2). I think it could be improved even more with some simple changes. Before I make the changes and create a PR I thought it would perhaps be good to first present the ideas and see what the reactions will be. Currently the health page looks like this:

<img width="1250" alt="Screenshot 2021-12-10 at 23 35 11" src="https://user-images.githubusercontent.com/18613261/145649881-90a8ccdf-6d92-415a-9031-edf2fd8fdcee.png">

The changes I have in mind will result into this:

![Laravel-Health-white](https://user-images.githubusercontent.com/18613261/145649194-0152d5b9-5eee-4def-882a-5493761199c0.jpg)

### Change 1. Simplify and make room
The current checks are place on a white panel which sits on top of a gray background. By replacing the coloured background of a check with a white background we can get rid of the larger white panel. We then have one element less and the checks are more uniform which make it look cleaner. It also provides a more flexible base for adding rich check data in the future maybe, like graphs and/or bar charts.

### Change 2. Remain recognisability
What I think is really good about the current version, is that you instantly see which check failed and which one passed. To remain that recognisability I created a new element for the checks to clearly communicate the status. To emphasize the status I applied an icon in the center of each element.

### Change 3. Improved readability
In the current version you have text in the checks that is the same color as the background, but in a different shade. Now that each check is white we can use black as the base color, which should result in a better readability.

### Change 4. Center align + logo/icon
By center aligning the title and the `update at` string we have things set up for a nice mobile view as well. By adding a small logo/icon in the form of a heartbeat (representing a check) gives this package a bit more character.

![Laravel-Health-white-mobile](https://user-images.githubusercontent.com/18613261/145654352-f54e286d-aec9-4046-bac9-046dc16d4d49.jpg)

### Bonus. Ideal for dark mode
The before mentioned changes will also make it very suitable to support dark mode.
 
![Laravel-Health-dark](https://user-images.githubusercontent.com/18613261/145652828-02e016dd-b429-4806-97bc-63913f24487d.jpg)

![Laravel-Health-mobile-light-dark](https://user-images.githubusercontent.com/18613261/145652885-cb09f14e-34d0-4af9-a355-fd6ddc16fffd.jpg)

### Figma links:

Desktop (2 pages) - https://www.figma.com/proto/FYVK5W5tiXCdT6Su6UoeSa/Laravel-Health?page-id=4%3A130&node-id=4%3A188&viewport=419%2C48%2C0.5&scaling=min-zoom

Mobile (2 pages) - https://www.figma.com/proto/FYVK5W5tiXCdT6Su6UoeSa/Laravel-Health?page-id=0%3A1&node-id=0%3A32&viewport=419%2C48%2C0.5&scaling=scale-down

### Feedback
Perhaps I took it a bit too far, but it was a fun challenge to see how far I could get with the ingredients that are currently available for this page. I'm looking forward to any feedback. If the reactions are positive I'm more than happy to provide the necessary changes via a PR.

**Comment by freekmurze** [comment]
Your design looks beautiful 😍 I would definitely welcome this as a PR. 

I've used Tailwinds CDN just to keep things simple, but if you prefer, you could also add the styles to the package itself, much like we did in [laravel-dashboard](https://github.com/spatie/laravel-dashboard/tree/main). You could use v3 of Tailwind in any case.

One thing that should be kept from the old design is that if the results are a little bit old, the "Last check..." should be visually emphasised a little bit, so users know there's a problem.

I'm launching this package somewhere mid next week with a stream / blog post / twitter fanfare. If you get your PR ready by then, I'll showcase your design on the stream, in screenshots, etc... (and of course give you the credits for it). I don't want to pressure you, so if you can't make it happen by then, that's fine too!

**Comment by nckrtl** [comment]
Thanks Freek, glad you like it. That sounds like a cool opportunity indeed. I should be able to get it ready on time and will make sure to use Tailwind v3 and maintain the visual emphasis for outdated results. I'll keep you posted, have a great weekend!

**Comment by freekmurze** [comment]
This has been implemented. Thanks again @nckrtl 👍
