### ISSUE TITLE
ScheduleCheckHeartbeatCommand not working if scheduled

### ISSUE THREAD

**Issue by leonnicklas** [spatie/laravel-health#56]
If I run `php artisan health:schedule-check-heartbeat` manually and run `health:check` afterwards, everything works fine and the **ScheduleCheck** returns **OK**. 

But if I run the command scheduled in my **Kernel.php** (like explained [in the docs](https://spatie.be/docs/laravel-health/v1/available-checks/schedule))
```php
protected function schedule(Schedule $schedule)
    {
        $schedule->command(\Spatie\Health\Commands\RunHealthChecksCommand::class)->everyMinute();
        $schedule->command(\Spatie\Health\Commands\ScheduleCheckHeartbeatCommand::class)->everyMinute();
    }
```
the command seems not to be working correctly and the **ScheduleCheck** returns **"The schedule did not run yet."** (or **"The last run of the schedule was more than 22 minutes ago."** if it was executed before manually).
___
**What I tried so far:**
- Reversing the order of execution -> did not help.
- Running `php artisan schedule:run` manually (no errors) -> did not work.
- Tried `ScheduleCheck::new()->heartbeatMaxAgeInMinutes(2),` optionally -> did not help.
- Configured a custom cache folder and linked it (works for manual execution) -> did not help.
- Used `use Spatie\Health\Commands\ScheduleCheckHeartbeatCommand;` instead of inline written -> did not help.
- Tried scheduling just the command itself directly like so: `$schedule->command('health:schedule-check-heartbeat')->everyMinute();` -> did not help.
___
**The problem in one line:**
The command `php artisan health:schedule-check-heartbeat` is only working manually, not if scheduled.
___
I did everything like in the docs and I'm running out of ideas...

⚠️ One thing I also tried returned an error (which I don't really know if it has something to do with it).
Running `php artisan schedule:list` resulted in the following error message:
```sh
TypeError 

  DateTime::setTimezone(): Argument #1 ($timezone) must be of type DateTimeZone, null given

  at vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleListCommand.php:42
     38▕                 $event->expression,
     39▕                 $event->description,
     40▕                 (new CronExpression($event->expression))
     41▕                             ->getNextRunDate(Carbon::now()->setTimezone($event->timezone))
  ➜  42▕                             ->setTimezone($this->option('timezone', config('app.timezone')))
     43▕                             ->format('Y-m-d H:i:s P'),
     44▕             ];
     45▕         }
     46▕ 

      +14 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by leonnicklas** [comment]
@freekmurze do you have any idea what the problem might be?

**Comment by freekmurze** [comment]
Not really, currently no time to investigate this further... If you discover an error with the package, do let me know!

**Comment by leonnicklas** [comment]
Found the problem... 

After configuring Oh Dear immediately after installing the package (not knowing that every time oh dear checks the data, in Laravel internally executes the command `health:check`), I thought that howsoever the cron job was running automatically because the results where refreshed automatically every minute 🤦🏼‍♂️ 
Of course it wasn't... (Didn't do anything with cron jobs until this day)

After setting up my cronjob as described and setting the `always_send_fresh_results` variable in the `health.php` config file to `false` everything is now working as expected!
