### ISSUE TITLE
No notification when DatabaseCheck fails

### ISSUE THREAD

**Issue by tekord** [spatie/laravel-health#77]
By default, the package is configured to store results into a database. Which is unavailable. And it is impossible to know that something went wrong due to missing notification ¯\_(ツ)_/¯

RunHealthChecksCommand.php file:

```
        if (! $this->option('do-not-store-results')) {
->            $this->storeResults($results);
        }

        if (! $this->option('no-notification')) {
->            $this->sendNotification($results);
        }
```

**Comment by freekmurze** [comment]
This has been fixed in the latest release.
